name: Next.js Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-nextjs:
    name: Build Next.js
    runs-on: ubuntu-latest
    steps:
      - name: First Step in Build
        run: echo "First Step in Build" > test1.txt
      

  test-nextjs:    
    name: Test Next.js
    runs-on: ubuntu-latest
    steps:
      - name: First Step in Test
        run: echo "First Step in Test" > test2.txt

  third-job:    
      name: Third Job
      needs: [build-nextjs, test-nextjs]
      runs-on: ubuntu-latest
      steps:
        - name: Third Step in Test
          run: ls -al
