name: Next.js Pipeline

on:
  push:
    branches:
      - master

jobs:
  job-build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: | 
          npm install \
          npm install -g netlify-cli

      - name: Build i
        run: npm i
      
      - name: Build
        run: npm run build       

      - name: List 1
        run: ls -l out

      - name: Upload Artifact       
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: out

      - name: List 2
        run: ls -l out

      - name: Deploy Artifact       
        run: |
          netlify deploy --prod \
            --dir=out \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
 