name: Next.js Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-nextjs:
    name: Build Next.js
    runs-on: ubuntu-latest
    steps:
      - name: First Step in Build
        run: echo "First Step in Build"
      
      - name: Create a File
        run: echo "First Step in Build" > test.txt

  test-nextjs:    
    name: Test Next.js
    needs: build-nextjs
    runs-on: ubuntu-latest
    steps:
      - name: First Step in Test
        run: ls -al

  if: ${{ github.ref == 'refs/heads/master' }}
  test-nextjs:    
      name: Third Job
      needs: [build-nextjs, Test Next.js]
      runs-on: ubuntu-latest
      steps:
        - name: Third Step in Test
          run: ls -al
